version: '3.4'

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3100:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=root:123456@tcp(mysql-aiapi:3306)/new-api  # 修改为新 mysql 容器名
      - REDIS_CONN_STRING=redis://redis-aiapi             # 修改为新 redis 容器名
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true
    #      - STREAMING_TIMEOUT=120
    #      - SESSION_SECRET=random_string
    #      - NODE_TYPE=slave
    #      - SYNC_FREQUENCY=60
    #      - FRONTEND_BASE_URL=https://openai.justsong.cn

    depends_on:
      - redis-aiapi
      - mysql-aiapi

    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-aiapi:
    image: redis:latest
    container_name: redis-aiapi
    restart: always

  mysql-aiapi:
    image: mysql:8.2
    container_name: mysql-aiapi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: new-api
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"

volumes:
  mysql_data:
